
exports.el = {
    home: '[class$=home]',
    products: '[href$=products]',
    cart: '[href$=cart]',
    signup: '[href$=login]',
    logout: '[href$=logout]',
    deleteAccount: '[href$=delete_account]',
    contactUs: '[href$=contact_us]',
    formRegisterNewUser: '.signup-form h2',
    inputName: '[data-qa="signup-name"]',
    inputEmail: '[data-qa="signup-email"]',
    btnSignup: '[data-qa="signup-button"]',
    titleUser: '[type=radio]',
    inputPassword: '[name=password]',
    birthDay: '[data-qa="days"]',
    birthMonth: '[name="months"]',
    birthYear: '[data-qa="years"]',
    newsletter: '#newsletter',
    offers: '#optin',
    inpFirstName: '#first_name',
    inpLastName: '#last_name',
    company: '[data-qa="company"]',
    address1: '[name="address1"]',
    address2: '[name="address2"]',
    selectCountry: '#country',
    inpState: '[name="state"]',
    inpCity: '[data-qa="city"]',
    inpZipcode: '[data-qa="zipcode"]',
    mobile: '.login-form #mobile_number',
    accountCreated: 'account_created',
    msgAccountCreated: '.title.text-center',
    carouselHome: '#slider-carousel .carousel-inner',
    logInEmail: '[data-qa="login-email"]',
    logInPassword: '[data-qa="login-password"]',
    logInBtnconfirm: '[data-qa="login-button"]',
    msgincorrectLogIn: '.login-form p',
    logguedIn: '.shop-menu li',
    msgEmailAlready: '.signup-form p',
    inpNameInContact: '[data-qa="name"]',
    inpEmailInContact: '[data-qa="email"]',
    inpSubjectInContact: '[data-qa="subject"]',
    msgInContact: '[data-qa="message"]',
    chooseFile: '[name="upload_file"]',
    btnSubmitForm: '[data-qa="submit-button"]',
    msgSubmittedForm: '.contact-form .alert-success',
    productList: '.single-products',
    productTitle: '.product-information h2',
    productInformations: '.product-information p',
    productValue: '.product-information span span',
    searchProduct: '#advertisement #search_product',
    btnSearchProduct: '#advertisement #submit_search',
    titleSearchedProducts: '.title.text-center',
    inputSubscription: '#susbscribe_email',
    btnSubscribe: '#subscribe',
    msgSubscribed: '.alert-success',
    btnContinue: '[data-qa="continue-button"]',
    addToCart: '.add-to-cart',
    btnContinueShopping: '.modal-confirm button',
    btnProceedToCheckout: '#do_action .check_out',
    addressTitle: '#address_delivery .address_title',
    addressFirstAndLastName: '#address_delivery .address_firstname',
    addressCompanyName: '#address_delivery .address_address1',
    addressStreet: '#address_delivery .address_address1',
    addressCity: '#address_delivery .address_city',
    addressCountry: '#address_delivery .address_country_name',
    addressPhone: '#address_delivery .address_phone',
    billingTitle: '.page-subheading',
    billingFirstAndLastName: '#address_invoice .address_firstname',
    billingCompanyName: '#address_invoice .address_address1',
    billingStreet: '#address_invoice .address_address1',
    billingCity: '#address_invoice .address_city',
    billingCountry: '#address_invoice .address_country_name',
    billingPhone: '#address_invoice .address_phone',
    menuTable: '.table .cart_menu td',
    productTable: '#product-1 td',
    totalAmount: '.cart_total_price',
    comment: '#ordermsg [name="message"]',
    btnPlaceOrder: '.btn.check_out',
    paymentTitle: '.step-one h2',
    ccdName: '[data-qa="name-on-card"]',
    ccdNumber: '[data-qa="card-number"]',
    ccdCvc: '[data-qa="cvc"]',
    ccdExpireMonth: '[data-qa="expiry-month"]',
    ccdExpireYear: '[data-qa="expiry-year"]',
    btnPayOrder: '[data-qa="pay-button"]',
    titleOrderPlaced: '[data-qa="order-placed"]',
    msgOrderConfirmed: '.container p'
}